import bcrypt from 'bcryptjs';

const data ={
  users: [
    {
      name: 'Hachem',
      email: 'admin@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
    },
    {
      name: 'Hedi',
      email: 'user@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
  ],
    products: [
  {
    name: 'lemon juice',
    category: 'Juice',
    image: '/images/product-1.jpg',
    price: 12,
    countInStock: 15,
    brand: ' DJOBENNA',
    rating: 4.5,
    numReviews: 10,
    description: 'high quality product',
  },
  {
    name: 'Strawberry juice',
    category: 'Juice',
    image: '/images/product-2.jpg',
    price: 6,
    countInStock: 5,
    brand: ' DJOBENNA',
    rating: 4.2,
    numReviews: 5,
    description: 'high quality product',
  },
  {
    name: 'dried fig juice',
    category: 'Juice',
    image: '/images/product-3.jpg',
    price: 10,
    countInStock: 10,
    brand: ' DJOBENNA',
    rating: 4.5,
    numReviews: 8,
    description: 'high quality product',
  }, 
  {
    name: 'FIG jam',
    category: 'Jam',
    image: '/images/product-4.jpg',
    price: 5,
    countInStock: 0,
    brand: ' DJOBENNA',
    rating: 4.5,
    numReviews: 8,
    description: 'high quality product',
  },
  {
    name: 'From Quince jam',
    category: 'Jam',
    image: '/images/product-5.jpg',
    price: 3,
    countInStock: 5,
    brand: ' DJOBENNA',
    rating: 4.5,
    numReviews: 8,
    description: 'high quality product',
  },
  {
    name: 'Strawberry jam',
    category: 'Jam',
    image: '/images/product-6.jpg',
    price: 4,
    countInStock: 12,
    brand: ' DJOBENNA',
    rating: 4.5,
    numReviews: 8,
    description: 'high quality product',
  },
],
};
export default data;